### ISSUE TITLE
How is this different from SimpleDTO?

### ISSUE THREAD

**Issue by hopeseekr** [MarvinWank/vog#2]
Hi, can you have a look at https://github.com/PHPExpertsInc/SimpleDTO and tell me what the differences are between this project and your project?

SimpleDTO allows the end-user to easily create immutable DTO objects using nothing but simple docblock notations...

There's no "code generation" or extra steps. You just set your docblocks and go!

For instance, the [**NeverBounce API Client's**](https://github.com/PHPExpertsInc/NeverBounce) SimpleDTO:

```php
/**
 * @see https://developers.neverbounce.com/docs/verifying-an-email
 *
 * @property-read string   $status
 * @property-read string   $result
 * @property-read string[] $flags
 * @property-read string   $suggested_correction
 * @property-read int      $execution_time
 */
final class EmailValidationDTO extends SimpleDTO
{
}
```

There's even really complex examples via that company's [**Zuora API Client**](https://github.com/PHPExpertsInc/Zuora-API-Client) DTOs, particularly the multi-leveled [**Write\AccountDTO.php**](https://github.com/PHPExpertsInc/Zuora-API-Client/blob/master/src/DTOs/Write/AccountDTO.php).

**Comment by MarvinWank** [comment]
Thanks for the suggestion. From my first glance it appears, that both projects do have a common goal in mind, but have a different approach to reach it. Additionally, vog has a broader target, as it not only generates DTOs, but also enums and possibly more artifacts in the future. 

To be brutally honest though, I wouldn't have written vog if I found your project first, but because of searching for the wrong things, I didn't. I personally don't like the dockblock syntax, but I would've definitely accepted it.

So essentially, the only really difference to the end user is the syntax and that vog has a somewhat broader aim.
